[project]
name = "repl-nix-altcoinpatternanalyzer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.0",
    "ccxt>=4.1.0",
    "cryptocompare>=0.7.6",
    "dataclasses>=0.8",
    "feedparser>=6.0.10",
    "nltk>=3.8.1",
    "numpy>=1.24.0",
    "openai>=1.54.3",
    "pandas>=2.1.0",
    "plotly>=5.17.0",
    "pycoingecko>=2.1.3",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
    "scikit-learn>=1.3.0",
    "seaborn",
    "spacy>=1.5.2",
    "streamlit>=1.28.0",
    "ta",
    "textblob>=0.18.0.post0",
    "tweepy>=4.14.0",
    "vadersentiment>=3.3.2",
    "yfinance",
]
