[project]
name = "repl-nix-altcoinpatternanalyzer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "ccxt>=4.4.29",
    "cryptocompare>=0.7.6",
    "dataclasses>=0.8",
    "feedparser>=6.0.10",
    "nltk>=3.8.1",
    "numpy",
    "openai>=1.54.3",
    "pandas>=2.0.0",
    "plotly>=5.18.0",
    "pycoingecko>=2.1.3",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "streamlit==1.40.0",
    "textblob>=0.18.0.post0",
    "tweepy>=4.14.0",
    "vadersentiment>=3.3.2",
]
