[server]
headless = true
enableCORS = true
address = "0.0.0.0"
port = 5000

[ui]
hideTopBar = true
hideSidebarNav = true

[theme]
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[browser]
serverAddress = "0.0.0.0"
serverPort = 5000
gatherUsageStats = false

[runner]
magicEnabled = true
fastRerenderEnabled = true
