[server]
headless = true
enableCORS = true
address = "0.0.0.0"
port = 5000

[browser]
serverAddress = "0.0.0.0"
serverPort = 5000
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[ui]
hideTopBar = true
hideSidebarNav = true

[client]
toolbarMode = "minimal"
showErrorDetails = true

[logger]
level = "info"
