[server]
port = 8501
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[ui]
hideTopBar = false
hideSidebarNav = false

[client]
toolbarMode = "minimal"
showErrorDetails = true

[logger]
level = "info"
