[server]
headless = true
enableCORS = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[logger]
level = "info"

[browser]
serverAddress = "0.0.0.0"
serverPort = 5000
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true

[runner]
magicEnabled = true
fastRerenderEnabled = true
